### ISSUE TITLE
docker-compose.yml Bug Report

### ISSUE THREAD

**Issue by vldMlvn** [Ne4upara/MarketPlace#74]
Here are the bugs I found in the code:

1. The version number in the first line is missing a closing single quote, it should be '3.7' instead of '3.
2. In the 'postgres' service, the 'ports' mapping for the container to the host machine is missing a digit, it should be '5432' instead of '543'.

Here is the corrected code:

```
# This is the version of the Docker Compose file format we are using.
version: '3.7'

# The 'postgres' service uses the 'postgres:latest' image to create a container
# running the latest version of PostgreSQL. It loads environment variables
# from a file named 'variables.env' and maps port 5432 from the container to
# the host machine.
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - variables.env
    ports:
      - '5432'

```
